MODULES = [
    {'id': 1, 'title': 'Computing, Mathematics & Quantum Foundations', 'desc': 'Classical computing, probability, linear algebra, and Dirac notation.', 'category': 'Foundations'},
    {'id': 2, 'title': 'Qubits & Quantum States', 'desc': 'Qubits, superposition, Bloch sphere, and measurement basics.', 'category': 'Foundations'},
    {'id': 3, 'title': 'Single-Qubit Quantum Gates', 'desc': 'Pauli gates, Hadamard, phase gates, and rotation gates.', 'category': 'Foundations'},
    {'id': 4, 'title': 'Multi-Qubit Systems & Entanglement', 'desc': 'Tensor products, CNOT, entanglement, and Bell states.', 'category': 'Foundations'},
    {'id': 5, 'title': 'Quantum Circuit Design', 'desc': 'Circuit structure, depth, width, composition, and optimization basics.', 'category': 'Foundations'},
    {'id': 6, 'title': 'Measurement & Quantum Information', 'desc': 'Measurement bases, observables, expectation values, and statistics.', 'category': 'Foundations'},
    {'id': 7, 'title': 'Quantum Programming with Qiskit', 'desc': 'Qiskit circuits, simulators, transpilation, and execution.', 'category': 'Intermediate'},
    {'id': 8, 'title': 'Quantum SDK Ecosystem', 'desc': 'Qiskit, PennyLane, Cirq comparison and hybrid programming.', 'category': 'Intermediate'},
    {'id': 9, 'title': 'Fundamental Quantum Algorithms', 'desc': 'Deutsch, Deutsch-Jozsa, Bernstein-Vazirani, Simon, teleportation, and superdense coding.', 'category': 'Intermediate'},
    {'id': 10, 'title': 'Advanced Quantum Algorithms', 'desc': "Grover's search, QFT, Shor's algorithm, and amplitude amplification.", 'category': 'Intermediate'},
    {'id': 11, 'title': 'Quantum Machine Learning', 'desc': 'Data encoding, parameterized circuits, VQC, and hybrid QML.', 'category': 'Advanced'},
    {'id': 12, 'title': 'Quantum Noise & NISQ', 'desc': 'Decoherence, error types, noise models, and fidelity.', 'category': 'Advanced'},
    {'id': 13, 'title': 'Quantum Error Correction', 'desc': 'Repetition codes, Shor code, Steane code, and surface codes.', 'category': 'Advanced'},
    {'id': 14, 'title': 'Quantum Circuit Optimization', 'desc': 'Gate cancellation, decomposition, transpilation, and resource estimation.', 'category': 'Advanced'},
    {'id': 15, 'title': 'Quantum Hardware & Real-World Computing', 'desc': 'Superconducting, trapped ion, photonic qubits, and the NISQ era.', 'category': 'Advanced'},
    {'id': 16, 'title': 'Capstone Projects', 'desc': 'Bell state, teleportation, Grover, classifier, and noise analysis projects.', 'category': 'Advanced'},
    {'id': 17, 'title': 'Quantum Research, Industry & Careers', 'desc': 'Research landscape, companies, career paths, papers, and portfolios.', 'category': 'Expert'},
    {'id': 18, 'title': 'Quantum Cryptography & Communication', 'desc': 'BB84, QKD, E91, post-quantum cryptography, and quantum signatures.', 'category': 'Expert'},
    {'id': 19, 'title': 'Variational Quantum & Optimization', 'desc': 'QAOA, VQE, QUBO, Ising model, and quantum annealing.', 'category': 'Expert'},
    {'id': 20, 'title': 'Quantum Networking & Distributed QC', 'desc': 'Quantum internet, repeaters, entanglement distribution, and cloud QC.', 'category': 'Expert'},
    {'id': 21, 'title': 'Applications, Industry & Careers', 'desc': 'Healthcare, finance, AI, sensing, and the quantum workforce.', 'category': 'Expert'},
    {'id': 22, 'title': 'Research Methodology & Projects', 'desc': 'Reading papers, reproducing experiments, benchmarking, and publishing.', 'category': 'Expert'},
    {'id': 23, 'title': 'Real Quantum Hardware & Cloud', 'desc': 'IBM Quantum, Amazon Braket, Azure Quantum, and hardware experiments.', 'category': 'Expert'},
    {'id': 24, 'title': 'Quantum Simulation', 'desc': 'Hamiltonian simulation, Trotterization, VQE, and molecular simulation.', 'category': 'Expert'},
]