import { useMemo, useState } from 'react';
import { MODULES, SKILL_LABELS } from '../../data/modules.js';

const students = [
  { name: 'Aarav Mehta', level: 'Intermediate', knowledge: 84, completed: 14, current: 15, strengths: 'Gates, Qiskit', weak: 'Noise & NISQ', assessment: 86, activity: 18, circuits: 12, lab: 5, status: 'On track' },
  { name: 'Priya Nair', level: 'Foundation', knowledge: 42, completed: 4, current: 5, strengths: 'Mathematics', weak: 'Entanglement, Circuits', assessment: 39, activity: 6, circuits: 2, lab: 0, status: 'Needs attention' },
  { name: 'Rohan Shah', level: 'Advanced', knowledge: 76, completed: 17, current: 18, strengths: 'Algorithms, QML', weak: 'Cryptography', assessment: 79, activity: 14, circuits: 19, lab: 8, status: 'On track' },
  { name: 'Zoya Khan', level: 'Foundation', knowledge: 51, completed: 6, current: 7, strengths: 'Qubits', weak: 'Programming, Measurement', assessment: 48, activity: 3, circuits: 1, lab: 1, status: 'Needs attention' },
  { name: 'Kabir Singh', level: 'Intermediate', knowledge: 68, completed: 11, current: 12, strengths: 'Circuit Design', weak: 'Quantum Noise', assessment: 64, activity: 11, circuits: 10, lab: 3, status: 'Review' },
  { name: 'Ananya Iyer', level: 'Advanced', knowledge: 91, completed: 21, current: 22, strengths: 'Research, Hardware', weak: 'Optimization', assessment: 94, activity: 21, circuits: 24, lab: 14, status: 'Top performer' },
];

const assessmentSeed = [
  { name: 'Module 5: Circuit Design Checkpoint', type: 'MCQ + Circuit', difficulty: 'Medium', duration: '25 min', assigned: 28, submissions: 22, average: 71, published: true },
  { name: 'Qiskit Foundations Lab', type: 'Coding', difficulty: 'Medium', duration: '40 min', assigned: 18, submissions: 11, average: 64, published: true },
  { name: 'Entanglement Retest', type: 'MCQ', difficulty: 'Easy', duration: '15 min', assigned: 9, submissions: 0, average: 0, published: false },
];

const tone = status => status === 'Needs attention' ? 'tag-danger' : status === 'Top performer' || status === 'On track' ? 'tag-success' : 'tag-warning';
const Meter = ({ value, danger = false }) => <div className="progress-bar"><div className={`progress-fill${danger ? '' : ' success'}`} style={{ width: `${value}%` }} /></div>;

export default function InstructorDashboard() {
  const [tab, setTab] = useState('overview');
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState('All students');
  const [selected, setSelected] = useState(students[1]);
  const [assessments, setAssessments] = useState(assessmentSeed);
  const [notice, setNotice] = useState('');
  const [modal, setModal] = useState(null);
  const visibleStudents = useMemo(() => students.filter(s => (filter === 'All students' || s.status === filter) && s.name.toLowerCase().includes(query.toLowerCase())), [query, filter]);
  const act = message => { setNotice(message); window.setTimeout(() => setNotice(''), 2600); };

  const tabs = [
    ['overview', 'Overview'], ['students', 'Students'], ['assessments', 'Assessments'], ['content', 'Learning Content'],
    ['paths', 'Learning Paths'], ['lab', 'Quantum Lab'], ['analytics', 'Analytics'], ['insights', 'AI Insights'], ['reports', 'Reports'], ['settings', 'Settings'],
  ];

  return <div className="page fade-in instructor-workspace">
    <div className="page-header instructor-header">
      <div><div className="eyebrow">INSTRUCTOR WORKSPACE · SIH 2026</div><h1 className="page-title">Teaching command center</h1><p className="page-subtitle">Monitor learning signals, intervene early, and guide every learner to the right next module.</p></div>
      <div className="instructor-actions"><button className="btn btn-secondary btn-sm" onClick={() => setModal({ kind: 'notifications' })}>🔔 3</button><button className="btn btn-primary" onClick={() => { setTab('assessments'); setModal({ kind: 'assessment' }); }}>+ Create assessment</button></div>
    </div>
    {notice && <div className="toast instructor-toast">✓ {notice}</div>}
    <div className="tabs instructor-tabs">{tabs.map(([id, label]) => <div key={id} className={`tab ${tab === id ? 'active' : ''}`} onClick={() => setTab(id)}>{label}</div>)}</div>

    {tab === 'overview' && <Overview onStudents={() => setTab('students')} onInsights={() => setTab('insights')} act={act} open={setModal} />}
    {tab === 'students' && <Students selected={selected} setSelected={setSelected} students={visibleStudents} query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} act={act} open={setModal} />}
    {tab === 'assessments' && <Assessments assessments={assessments} setAssessments={setAssessments} act={act} open={setModal} />}
    {tab === 'content' && <Content act={act} open={setModal} />}
    {tab === 'paths' && <Paths />}
    {tab === 'lab' && <Lab act={act} open={setModal} />}
    {tab === 'analytics' && <Analytics act={act} />}
    {tab === 'insights' && <Insights onStudents={() => setTab('students')} onAssessments={() => setTab('assessments')} act={act} />}
    {tab === 'reports' && <Reports act={act} open={setModal} />}
    {tab === 'settings' && <Settings act={act} />}
    {modal && <WorkspaceModal modal={modal} close={() => setModal(null)} assessments={assessments} setAssessments={setAssessments} act={act} />}
  </div>;
}

function Overview({ onStudents, onInsights, act, open }) {
  const stats = [['Total Students', '32', 'Across 3 active cohorts'], ['Active Students', '27', '84% active this week'], ['Assessments Completed', '118', '+16 since Monday'], ['Average Knowledge Score', '72%', 'Across 14 skill areas'], ['Course Completion Rate', '46%', '11.1 modules on average'], ['Need Attention', '5', 'Below 55% knowledge']];
  return <>
    <div className="grid grid-3 instructor-stats">{stats.map(([label, value, hint], index) => <div className="stat-card" key={label}><div className="stat-value">{value}</div><div className="stat-label">{label}</div><div className={index === 5 ? 'metric-alert' : 'metric-hint'}>{hint}</div></div>)}</div>
    <div className="instructor-question-grid">
      <section className="card question-card"><span className="question-kicker">WHO IS STRUGGLING?</span><h3>5 learners need intervention</h3><p>Priya and Zoya have low assessment scores and have not reached the expected circuit practice activity.</p><button className="btn btn-secondary btn-sm" onClick={onStudents}>View student signals →</button></section>
      <section className="card question-card"><span className="question-kicker">WHY?</span><h3>Entanglement is the main blocker</h3><p>Module 4 has the lowest first-attempt score (48%). Measurement and Qiskit setup are the next weak concepts.</p><button className="btn btn-secondary btn-sm" onClick={onInsights}>See AI diagnosis →</button></section>
      <section className="card question-card"><span className="question-kicker">WHAT NEXT?</span><h3>Assign the Bell-state practice path</h3><p>Use the guided circuit challenge, then retest with an 8-question checkpoint before Module 5.</p><button className="btn btn-primary btn-sm" onClick={onInsights}>Review recommendation</button></section>
    </div>
    <div className="grid grid-2" style={{ marginTop: 20 }}><section className="card"><div className="section-title"><div><h3>Students needing attention</h3><p>Prioritized by low knowledge score and recent activity.</p></div><span className="tag tag-danger">5 flagged</span></div><StudentRows compact /></section><section className="card"><div className="section-title"><div><h3>Latest notifications</h3><p>Events requiring an instructor decision.</p></div><button className="btn btn-secondary btn-sm" onClick={() => open({ kind: 'notifications' })}>View all</button></div><div className="activity-list"><Activity label="Priya Nair failed Entanglement Retest" meta="Assessment · 12 min ago" type="alert" /><Activity label="Rohan Shah completed Module 17" meta="Module completion · 48 min ago" /><Activity label="QPU job QL-8291 completed" meta="Quantum Lab · 1 hr ago" /><Activity label="8 new circuit submissions await review" meta="Circuit Design Checkpoint · Today" /></div></section></div>
  </>;
}

function Students({ students: rows, selected, setSelected, query, setQuery, filter, setFilter, act, open }) { return <>
  <div className="card instructor-toolbar"><input className="form-input" placeholder="Search students by name..." value={query} onChange={e => setQuery(e.target.value)} /><select className="form-select" value={filter} onChange={e => setFilter(e.target.value)}><option>All students</option><option>Needs attention</option><option>Review</option><option>On track</option><option>Top performer</option></select></div>
  <div className="grid grid-2"><section className="card roster-card"><div className="section-title"><div><h3>Student progress</h3><p>{rows.length} learners matching this view</p></div></div><div className="student-table">{rows.map(student => <button className={`student-row ${selected.name === student.name ? 'selected' : ''}`} key={student.name} onClick={() => setSelected(student)}><span><strong>{student.name}</strong><small>{student.level} · Module {student.current}</small></span><span className="student-score">{student.knowledge}%<small>{student.completed}/24 modules</small></span><span className={`tag ${tone(student.status)}`}>{student.status}</span></button>)}</div></section>
  <section className="card student-detail"><div className="section-title"><div><span className={`tag ${tone(selected.status)}`}>{selected.status}</span><h3 style={{ marginTop: 10 }}>{selected.name}</h3><p>{selected.level} learner · Current module {selected.current}</p></div><button className="btn btn-secondary btn-sm" onClick={() => open({ kind: 'message', student: selected })}>Message</button></div><div className="detail-score"><strong>{selected.knowledge}%</strong><span>Knowledge percentage</span></div><Meter value={selected.knowledge} danger={selected.knowledge < 55} /><div className="detail-grid"><Info label="Assessment average" value={`${selected.assessment}%`} /><Info label="Completed modules" value={`${selected.completed} / 24`} /><Info label="Circuit activity" value={`${selected.circuits} builds`} /><Info label="Quantum Lab" value={`${selected.lab} experiments`} /></div><div className="strength-grid"><div><small>STRENGTHS</small><p>{selected.strengths}</p></div><div><small>WEAK AREAS</small><p className="weak-text">{selected.weak}</p></div></div><button className="btn btn-primary btn-sm" style={{ marginTop: 18 }} onClick={() => open({ kind: 'support', student: selected })}>Assign support path</button></section></div>
  </>;
}

function Assessments({ assessments, setAssessments, act, open }) { return <><div className="section-title"><div><h2>Assessment studio</h2><p>Build targeted checks with MCQs, code execution, and circuit-building questions.</p></div><button className="btn btn-primary" onClick={() => open({ kind: 'assessment' })}>+ New assessment</button></div><div className="card table-card"><table><thead><tr><th>Assessment</th><th>Format</th><th>Difficulty / time</th><th>Submissions</th><th>Average</th><th>Status</th><th /></tr></thead><tbody>{assessments.map((a, i) => <tr key={`${a.name}-${i}`}><td><strong>{a.name}</strong><small>{a.assigned} students assigned</small></td><td>{a.type}</td><td>{a.difficulty}<small>{a.duration}</small></td><td>{a.submissions}/{a.assigned}</td><td>{a.average ? `${a.average}%` : '—'}</td><td><button className={`tag ${a.published ? 'tag-success' : 'tag-warning'}`} onClick={() => { const copy = [...assessments]; copy[i] = { ...a, published: !a.published }; setAssessments(copy); act(copy[i].published ? 'Assessment published.' : 'Assessment moved to draft.'); }}>{a.published ? 'Published' : 'Draft'}</button></td><td><button className="text-action" onClick={() => open({ kind: 'assessment', assessment: a, index: i })}>Edit</button> <button className="text-action danger" onClick={() => { setAssessments(assessments.filter((_, x) => x !== i)); act('Assessment deleted.'); }}>Delete</button></td></tr>)}</tbody></table></div><div className="grid grid-3" style={{ marginTop: 20 }}><Panel title="Question bank" text="MCQs, code editors, circuit targets, and rubrics ready to reuse." action="Manage bank" onAction={() => open({ kind: 'bank' })} /><Panel title="Submissions" text="22 responses require review; 8 include circuit-building work." action="Review submissions" onAction={() => open({ kind: 'submissions' })} /><Panel title="Performance" text="Entanglement questions have a 48% success rate." action="Open analysis" onAction={() => open({ kind: 'analysis' })} /></div></> }

function Content({ act, open }) { const groups = [['Course modules', '24 published modules', 'Edit structure', 'structure'], ['Topics & notes', '126 learning topics and instructor notes', 'Manage topics', 'topics'], ['Videos & demos', '38 videos · 12 practical demonstrations', 'Add resource', 'resource'], ['Practice library', '214 questions · 36 circuit challenges', 'Open library', 'library']]; return <><div className="section-title"><div><h2>Learning content</h2><p>Maintain the teaching material that powers learner roadmaps.</p></div><button className="btn btn-primary" onClick={() => open({ kind: 'resource' })}>+ Add resource</button></div><div className="grid grid-2">{groups.map(([title, text, action, kind]) => <Panel key={title} title={title} text={text} action={action} onAction={() => open({ kind })} />)}</div><section className="card" style={{ marginTop: 20 }}><h3>Quantum algorithm demonstrations</h3><p className="muted-copy">Bell states, Deutsch-Jozsa, Grover, QFT, VQE, QAOA and Shor demonstrations are available for assignment and lab linking.</p><div className="chip-row">{['Bell state', 'Grover', 'QFT', 'VQE', 'QAOA', 'Shor'].map(x => <button className="tag tag-accent" key={x} onClick={() => open({ kind: 'algorithm', algorithm: x })}>{x}</button>)}</div></section></> }

function Paths() { const difficult = MODULES.filter(m => [4, 7, 10, 12, 13].includes(m.id)); return <><div className="section-title"><div><h2>Learning paths</h2><p>Use the canonical roadmap and targeted support paths together.</p></div><span className="tag tag-accent">24-module roadmap</span></div><div className="grid grid-2"><section className="card"><h3>Personalized path queue</h3><div className="activity-list"><Activity label="Priya: Bell State Foundations → Module 5" meta="Weak in entanglement · assign 3 circuit challenges" type="alert" /><Activity label="Zoya: Measurement recovery path" meta="Retest after Module 6 video + practice" type="alert" /><Activity label="Kabir: NISQ readiness path" meta="Noise model lab before Module 13" /></div></section><section className="card"><h3>Difficult modules</h3>{difficult.map(m => <div className="module-line" key={m.id}><span><strong>M{m.id}</strong> {m.title}</span><span className="tag tag-warning">Review resource</span></div>)}</section></div></> }

function Lab({ act, open }) { const jobs = [['Circuit simulator', 'Priya Nair', 'Bell state · 1,024 shots', 'Completed'], ['Qiskit Aer', 'Rohan Shah', 'Grover search · 4 qubits', 'Completed'], ['IBM QPU', 'Ananya Iyer', 'VQE hydrogen experiment', 'Running'], ['PennyLane', 'Kabir Singh', 'Variational classifier', 'Review needed'], ['Cirq', 'Aarav Mehta', 'QFT benchmark', 'Completed']]; return <><div className="section-title"><div><h2>Quantum Lab monitor</h2><p>Observe student circuits, simulators, SDK experiments, and cloud-QPU submissions.</p></div><button className="btn btn-secondary" onClick={() => act('Lab activity refreshed.')}>Refresh activity</button></div><div className="grid grid-4 instructor-stats"><div className="stat-card"><div className="stat-value">86</div><div className="stat-label">Circuit runs today</div></div><div className="stat-card"><div className="stat-value">24</div><div className="stat-label">SDK experiments</div></div><div className="stat-card"><div className="stat-value">3</div><div className="stat-label">QPU submissions</div></div><div className="stat-card"><div className="stat-value">2</div><div className="stat-label">Results awaiting review</div></div></div><div className="card table-card" style={{ marginTop: 20 }}><table><thead><tr><th>Environment</th><th>Student</th><th>Experiment</th><th>Execution status</th><th /></tr></thead><tbody>{jobs.map(job => <tr key={job.join()}><td><strong>{job[0]}</strong></td><td>{job[1]}</td><td>{job[2]}</td><td><span className={`tag ${job[3] === 'Completed' ? 'tag-success' : job[3] === 'Running' ? 'tag-accent' : 'tag-warning'}`}>{job[3]}</span></td><td><button className="text-action" onClick={() => open({ kind: 'result', job })}>View result</button></td></tr>)}</tbody></table></div></> }

function Analytics({ act }) { return <><div className="section-title"><div><h2>Learning analytics</h2><p>Performance signals across topics, modules, assessments, and activity.</p></div><button className="btn btn-secondary" onClick={() => act('Analytics snapshot exported for the SIH demo.')}>Export snapshot</button></div><div className="grid grid-2"><section className="card"><h3>Topic-wise performance</h3>{[['Qubits & states', 82], ['Quantum gates', 76], ['Entanglement', 48], ['Qiskit programming', 63], ['Noise & NISQ', 54]].map(([x, v]) => <Bar key={x} label={x} value={v} />)}</section><section className="card"><h3>Module completion</h3>{[['Foundations', 78], ['Intermediate', 53], ['Advanced', 31], ['Expert', 14]].map(([x, v]) => <Bar key={x} label={x} value={v} />)}</section><section className="card"><h3>Top performers</h3><Activity label="Ananya Iyer · 91% knowledge score" meta="21 modules · 14 lab experiments" /><Activity label="Aarav Mehta · 84% knowledge score" meta="14 modules · 12 circuit builds" /></section><section className="card"><h3>Weak-area watchlist</h3><Activity label="Entanglement · 48% assessment accuracy" meta="Prioritize a guided Bell state lesson" type="alert" /><Activity label="Noise & NISQ · 54% assessment accuracy" meta="Assign simulator walkthrough" type="alert" /></section></div></> }

function Insights({ onStudents, onAssessments, act }) { return <><div className="section-title"><div><h2>AI teaching insights</h2><p>Recommended interventions derived from learner progress, assessments, and lab activity.</p></div><span className="tag tag-accent">Updated now</span></div><div className="insight-stack"><Insight title="Intervene with Priya and Zoya this week" body="Both are below the 55% knowledge threshold. Their scores drop after Module 3, and neither has completed more than two circuit challenges." next="Assign the Bell State Foundations path: Module 4 recap video, 3 guided circuits, then an 8-question retest." action="Open students" onAction={onStudents} /><Insight title="Repair the entanglement learning sequence" body="Entanglement has the lowest topic accuracy (48%) and creates a completion bottleneck from Module 4 to Module 5." next="Add the visual Bell-pair demonstration before the assessment and publish the Entanglement Retest." action="Open assessment" onAction={onAssessments} /><Insight title="Challenge advanced learners with QPU work" body="Ananya and Rohan consistently finish practical work above cohort average and show high Quantum Lab activity." next="Assign VQE/QAOA experiments with a cloud-QPU reflection rubric." action="View lab plan" onAction={() => act('Advanced QPU lab plan opened.')} /></div></> }

function Reports({ act, open }) { return <><div className="section-title"><div><h2>Reports</h2><p>Produce shareable summaries for learners, mentors, and program reviewers.</p></div></div><div className="grid grid-3">{[['Student performance', 'Knowledge, strengths, assessments, and next steps'], ['Module completion', 'Cohort progress, drop-off, and completion rates'], ['Assessment analysis', 'Question-level score and submission data'], ['Weak-area report', 'At-risk learners and recommended interventions'], ['Activity report', 'Learning time, circuits, Lab, and QPU activity'], ['SIH demo brief', 'Platform impact snapshot for presentation']].map(([title, text]) => <Panel key={title} title={title} text={text} action="Generate report" onAction={() => open({ kind: 'report', title, text })} />)}</div></> }

function Settings({ act }) { return <div className="grid grid-2"><section className="card"><h2>Instructor profile</h2><div className="form-group"><label className="form-label">Display name</label><input className="form-input" defaultValue="Dr. Quantum Instructor" /></div><div className="form-group"><label className="form-label">Email</label><input className="form-input" defaultValue="instructor@gmail.com" /></div><button className="btn btn-primary" onClick={() => act('Instructor profile saved.')}>Save profile</button></section><section className="card"><h2>Notifications</h2><div className="settings-list">{['New assessment submissions', 'Module completions', 'Failed assessments', 'Cloud-QPU job completion', 'Weekly cohort summary'].map((x, i) => <label key={x}><input type="checkbox" defaultChecked={i < 4} /> {x}</label>)}</div><button className="btn btn-secondary" onClick={() => act('Notification settings saved.')}>Save preferences</button></section></div> }

function StudentRows({ compact = false }) { return <div className="activity-list">{students.filter(s => s.status === 'Needs attention' || s.status === 'Review').slice(0, compact ? 4 : 6).map(s => <div className="attention-row" key={s.name}><div><strong>{s.name}</strong><p>{s.weak} · Module {s.current}</p></div><div><strong>{s.knowledge}%</strong><span className={`tag ${tone(s.status)}`}>{s.status}</span></div></div>)}</div> }
function Activity({ label, meta, type }) { return <div className={`activity-item ${type || ''}`}><span className="activity-dot" /><div><strong>{label}</strong><p>{meta}</p></div></div> }
function Info({ label, value }) { return <div><small>{label}</small><strong>{value}</strong></div> }
function Panel({ title, text, action, onAction }) { return <section className="card compact-panel"><h3>{title}</h3><p>{text}</p><button className="text-action" onClick={onAction}>{action} →</button></section> }
function Bar({ label, value }) { return <div className="bar-line"><div><span>{label}</span><strong>{value}%</strong></div><Meter value={value} danger={value < 60} /></div> }
function Insight({ title, body, next, action, onAction }) { return <section className="card insight-card"><span className="question-kicker">AI RECOMMENDATION</span><h3>{title}</h3><p>{body}</p><div className="next-step"><strong>Recommended next step</strong><span>{next}</span></div><button className="btn btn-primary btn-sm" onClick={onAction}>{action}</button></section> }

function WorkspaceModal({ modal, close, assessments, setAssessments, act }) {
  const [draft, setDraft] = useState(modal.assessment || { name: '', type: 'MCQ + Coding + Circuit', difficulty: 'Medium', duration: '30 min', assigned: 0, submissions: 0, average: 0, published: false });
  const saveAssessment = () => {
    if (!draft.name.trim()) return;
    const record = { ...draft, name: draft.name.trim(), assigned: Number(draft.assigned || 0) };
    setAssessments(modal.index === undefined ? [...assessments, record] : assessments.map((item, index) => index === modal.index ? record : item));
    act(modal.index === undefined ? 'Assessment created successfully.' : 'Assessment updated successfully.'); close();
  };
  const reportDetails = {
    'Student performance': { heading: 'Learner scorecard', metrics: [['Top performer', 'Ananya Iyer · 91%'], ['Needs support', 'Priya Nair · 42%'], ['Cohort average', '72%']], lines: ['Priya: strengthen entanglement and circuit design before Module 5.', 'Zoya: reinforce measurement and Qiskit foundations.', 'Ananya: assign advanced QPU/VQE work.'] },
    'Module completion': { heading: 'Curriculum completion', metrics: [['Foundations', '78%'], ['Intermediate', '53%'], ['Advanced', '31%']], lines: ['Largest drop-off: Module 4 → Module 5.', 'Module 4 Entanglement has the lowest first-attempt score.', 'Recommended: release a Bell-state practice path before Module 5.'] },
    'Assessment analysis': { heading: 'Assessment quality', metrics: [['Checkpoint submissions', '22 / 28'], ['Average score', '71%'], ['Hardest question type', 'Circuit building · 48%']], lines: ['MCQ accuracy: 74%.', 'Coding accuracy: 66%.', 'Circuit-building accuracy: 48%; add guided examples before retesting.'] },
    'Weak-area report': { heading: 'Intervention watchlist', metrics: [['At-risk students', '5'], ['Weakest topic', 'Entanglement · 48%'], ['Next intervention', 'Bell State Foundations']], lines: ['Priya Nair and Zoya Khan should receive a targeted support path.', 'Noise & NISQ is the second-lowest topic at 54%.', 'Schedule the Entanglement Retest after three guided circuits.'] },
    'Activity report': { heading: 'Learning activity', metrics: [['Active this week', '27 / 32'], ['Circuit runs today', '86'], ['Cloud-QPU jobs', '3']], lines: ['Ananya Iyer has 14 Quantum Lab experiments.', 'Aarav Mehta has created 12 circuit builds.', 'Five learners have fewer than five activities this week.'] },
    'SIH demo brief': { heading: 'SIH 2026 impact snapshot', metrics: [['Learners tracked', '32'], ['Modules', '24'], ['AI interventions', '5 active']], lines: ['QuantumLearn links diagnostic assessment, adaptive paths, circuit practice, and instructor intervention.', 'The instructor view identifies who is struggling, why, and the recommended next action.', 'Demonstrate the Bell State Foundations intervention for the clearest end-to-end story.'] },
  };
  const activeReport = reportDetails[modal.title] || { heading: 'Instructor report', metrics: [], lines: [] };
  const downloadReport = () => {
    const report = `${modal.title}\nQuantumLearn AI · Instructor report\n\n${modal.text}\n\n${activeReport.metrics.map(([label, value]) => `${label}: ${value}`).join('\n')}\n\n${activeReport.lines.join('\n')}\n`;
    const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([report], { type: 'text/plain' })); link.download = `${modal.title.toLowerCase().replaceAll(' ', '-')}-report.txt`; link.click(); URL.revokeObjectURL(link.href); act(`${modal.title} report downloaded.`);
  };
  let title = 'Instructor tool'; let body = null;
  if (modal.kind === 'assessment') { title = modal.assessment ? 'Edit assessment' : 'Create assessment'; body = <div className="modal-form"><label>Assessment title<input className="form-input" value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} placeholder="e.g. Module 4 checkpoint" /></label><label>Question format<select className="form-select" value={draft.type} onChange={e => setDraft({ ...draft, type: e.target.value })}><option>MCQ</option><option>Coding</option><option>Circuit building</option><option>MCQ + Coding + Circuit</option></select></label><div className="modal-form-row"><label>Difficulty<select className="form-select" value={draft.difficulty} onChange={e => setDraft({ ...draft, difficulty: e.target.value })}><option>Easy</option><option>Medium</option><option>Hard</option></select></label><label>Time limit<input className="form-input" value={draft.duration} onChange={e => setDraft({ ...draft, duration: e.target.value })} /></label></div><label>Students assigned<input className="form-input" type="number" min="0" value={draft.assigned} onChange={e => setDraft({ ...draft, assigned: e.target.value })} /></label><div className="modal-footer"><button className="btn btn-secondary" onClick={close}>Cancel</button><button className="btn btn-primary" onClick={saveAssessment}>{modal.assessment ? 'Save changes' : 'Create assessment'}</button></div></div>; }
  if (modal.kind === 'bank') { title = 'Question bank'; body = <ToolList intro="Reusable questions ready for assessment builders." rows={['12 MCQs: Qubits and states', '8 coding tasks: Qiskit foundations', '9 circuit targets: Bell state and CNOT', '6 rubrics: Algorithm implementation']} action="Add question" onAction={() => act('Question draft added to the bank.')} />; }
  if (modal.kind === 'submissions') { title = 'Submission review'; body = <ToolList intro="Review learner attempts and provide actionable feedback." rows={['Priya Nair · Entanglement Retest · 39%', 'Kabir Singh · Qiskit Foundations Lab · 64%', 'Aarav Mehta · Circuit Design Checkpoint · 86%']} action="Mark reviewed" onAction={() => act('Submission marked as reviewed.')} />; }
  if (modal.kind === 'analysis') { title = 'Assessment performance analysis'; body = <><div className="modal-metrics"><Info label="Responses" value="22 / 28" /><Info label="Average score" value="71%" /><Info label="Hardest skill" value="Entanglement" /></div><Bar label="MCQ accuracy" value={74} /><Bar label="Coding accuracy" value={66} /><Bar label="Circuit accuracy" value={48} /></>; }
  if (modal.kind === 'structure') { title = 'Course structure manager'; body = <ToolList intro="Manage the 24-module curriculum order and visibility." rows={MODULES.slice(0, 8).map(m => `M${m.id} · ${m.title}`)} action="Save module order" onAction={() => act('Course structure saved.')} />; }
  if (modal.kind === 'topics') { title = 'Topics & notes manager'; body = <ToolList intro="Edit topic content, teaching notes, videos, and practical demonstrations." rows={['Module 4 · Bell pairs and entanglement', 'Module 5 · Circuit depth and composition', 'Module 7 · Qiskit simulator walkthrough', 'Module 12 · Noise models']} action="Add topic" onAction={() => act('New topic draft added.')} />; }
  if (modal.kind === 'resource') { title = 'Add learning resource'; body = <ResourceForm close={close} act={act} />; }
  if (modal.kind === 'library') { title = 'Practice library'; body = <ToolList intro="Practice content can be assigned to an individual or cohort." rows={['214 MCQs across 24 modules', '36 circuit-building challenges', '18 code exercises for Qiskit, PennyLane, and Cirq']} action="Assign selected practice" onAction={() => act('Practice assignment created.')} />; }
  if (modal.kind === 'algorithm') { title = `${modal.algorithm} demonstration`; body = <><p className="muted-copy">This practical demonstration can be attached to a module, assigned to a cohort, or opened in Quantum Lab.</p><div className="modal-footer"><button className="btn btn-secondary" onClick={() => act(`${modal.algorithm} opened in Quantum Lab.`)}>Open in Lab</button><button className="btn btn-primary" onClick={() => act(`${modal.algorithm} assigned to the active cohort.`)}>Assign to cohort</button></div></>; }
  if (modal.kind === 'result') { title = `${modal.job[2]} · execution result`; body = <><div className="modal-metrics"><Info label="Environment" value={modal.job[0]} /><Info label="Student" value={modal.job[1]} /><Info label="Status" value={modal.job[3]} /></div><pre className="result-code">{'{\n  "shots": 1024,\n  "success_probability": 0.982,\n  "result": "Execution data available"\n}'}</pre><button className="btn btn-primary" onClick={() => act('Execution result marked as reviewed.')}>Mark reviewed</button></>; }
  if (modal.kind === 'report') { title = `${modal.title} report`; body = <><p className="muted-copy">{modal.text}</p><div className="modal-metrics">{activeReport.metrics.map(([label, value]) => <Info key={label} label={label} value={value} />)}</div><div className="report-preview"><strong>{activeReport.heading}</strong>{activeReport.lines.map(line => <p key={line}>{line}</p>)}</div><div className="modal-footer"><button className="btn btn-secondary" onClick={close}>Close</button><button className="btn btn-primary" onClick={downloadReport}>Download report</button></div></>; }
  if (modal.kind === 'notifications') { title = 'Notifications'; body = <ToolList intro="Recent instructor events" rows={['Priya Nair failed Entanglement Retest', '8 circuit submissions await review', 'IBM QPU job QL-8291 completed']} action="Mark all read" onAction={() => act('All notifications marked as read.')} />; }
  if (modal.kind === 'message') { title = `Message ${modal.student.name}`; body = <MessageForm close={close} act={act} student={modal.student} />; }
  if (modal.kind === 'support') { title = `Assign support path · ${modal.student.name}`; body = <><p className="muted-copy">Assign Bell State Foundations: Module 4 recap, three guided circuits, and the Entanglement Retest.</p><div className="modal-footer"><button className="btn btn-secondary" onClick={close}>Cancel</button><button className="btn btn-primary" onClick={() => { act(`Support path assigned to ${modal.student.name}.`); close(); }}>Assign path</button></div></>; }
  return <div className="modal-overlay" onMouseDown={close}><div className="modal instructor-modal" onMouseDown={e => e.stopPropagation()}><div className="modal-header"><h2>{title}</h2><button className="btn btn-secondary btn-sm" onClick={close}>Close</button></div>{body}</div></div>;
}
function ToolList({ intro, rows, action, onAction }) { return <><p className="muted-copy">{intro}</p><div className="tool-list">{rows.map(row => <div key={row}>{row}</div>)}</div><button className="btn btn-primary" onClick={onAction}>{action}</button></>; }
function ResourceForm({ close, act }) { const [name, setName] = useState(''); return <div className="modal-form"><label>Resource title<input className="form-input" value={name} onChange={e => setName(e.target.value)} placeholder="e.g. Bell state visual guide" /></label><label>Resource type<select className="form-select"><option>Video</option><option>Note</option><option>Practical demonstration</option><option>External learning link</option></select></label><label>Link or description<textarea className="form-textarea" placeholder="Add the resource URL or a concise description" /></label><div className="modal-footer"><button className="btn btn-secondary" onClick={close}>Cancel</button><button className="btn btn-primary" onClick={() => { if (name.trim()) { act(`${name} added to learning content.`); close(); } }}>Add resource</button></div></div>; }
function MessageForm({ close, act, student }) { const [text, setText] = useState(`Hi ${student.name}, I recommend completing the guided practice before your next checkpoint.`); return <div className="modal-form"><label>Message<textarea className="form-textarea" value={text} onChange={e => setText(e.target.value)} /></label><div className="modal-footer"><button className="btn btn-secondary" onClick={close}>Cancel</button><button className="btn btn-primary" onClick={() => { if (text.trim()) { act(`Message sent to ${student.name}.`); close(); } }}>Send message</button></div></div>; }
