import { useEffect, useState } from 'react';
import { adminApi } from '../../services/quantumApi.js';

const sections = [['overview', 'Overview'], ['users', 'Users'], ['modules', 'Modules'], ['topics', 'Topics'], ['resources', 'Resources'], ['questions', 'Questions'], ['circuit-challenges', 'Circuit challenges'], ['coding-challenges', 'Coding challenges'], ['achievements', 'Achievements'], ['projects', 'Projects'], ['announcements', 'Announcements'], ['settings', 'Settings'], ['audit', 'Audit log']];
const contentSections = new Set(sections.map(([key]) => key).filter(key => !['overview', 'users', 'settings', 'audit'].includes(key)));

export default function AdminPanel() {
  const [section, setSection] = useState('overview'); const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [query, setQuery] = useState(''); const [editor, setEditor] = useState(null); const [roleSaving, setRoleSaving] = useState('');
  const load = async () => { setLoading(true); setError(''); try { const response = section === 'overview' ? await adminApi.dashboard() : section === 'users' ? await adminApi.users(query) : section === 'settings' ? await adminApi.settings() : section === 'audit' ? await adminApi.auditLogs() : await adminApi.content(section, query); setData(response); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  useEffect(() => { setQuery(''); setEditor(null); load(); }, [section]);
  const saveContent = async values => { try { if (editor?.id) await adminApi.updateContent(section, editor.id, values); else await adminApi.createContent(section, values); setEditor(null); setNotice('Saved.'); load(); } catch (e) { setError(e.message); throw e; } };
  const archive = async row => { if (!window.confirm(`Archive "${row.title}"? Historical records will be preserved.`)) return; try { await adminApi.archiveContent(section, row.id); setNotice('Archived.'); load(); } catch (e) { setError(e.message); } };
  const updateRole = async (id, role) => { setRoleSaving(id); try { await adminApi.updateUserRole(id, role); setNotice('User role updated.'); load(); } catch (e) { setError(e.message); } finally { setRoleSaving(''); } };
  const saveSettings = async values => { try { await adminApi.updateSettings(values); setNotice('Settings saved.'); load(); } catch (e) { setError(e.message); throw e; } };
  const rows = data?.items || data?.users || data?.logs || []; const title = sections.find(([key]) => key === section)?.[1];
  return <div className="page fade-in"><div className="page-header"><h1 className="page-title">Admin Dashboard</h1><p className="page-subtitle">Secure management for platform content and operations.</p></div><div className="tabs" style={{ marginBottom: 18, overflowX: 'auto' }}>{sections.map(([key, name]) => <button key={key} className={`tab ${section === key ? 'active' : ''}`} onClick={() => setSection(key)}>{name}</button>)}</div>{notice && <div className="tag tag-success" style={{ marginBottom: 14 }}>{notice}</div>}{error && <div className="card" style={{ color: 'var(--danger)', marginBottom: 14 }}>{error} <button className="btn btn-secondary btn-sm" onClick={load}>Retry</button></div>}{section === 'overview' && <Overview data={data?.metrics} loading={loading} refresh={load} />}{section === 'users' && <Users rows={rows} loading={loading} query={query} setQuery={setQuery} refresh={load} updateRole={updateRole} saving={roleSaving} />}{section === 'settings' && <Settings data={data?.settings} loading={loading} save={saveSettings} />}{section === 'audit' && <Records rows={rows} loading={loading} audit refresh={load} />}{contentSections.has(section) && <Content title={title} rows={rows} loading={loading} query={query} setQuery={setQuery} refresh={load} create={() => setEditor({})} edit={setEditor} archive={archive} />}{editor && <Editor value={editor} title={title} close={() => setEditor(null)} save={saveContent} />}</div>;
}

function Overview({ data, loading, refresh }) { const cards = [['Users', data?.total_users], ['Modules', data?.total_modules], ['Published modules', data?.published_modules], ['Topics', data?.total_topics], ['Contests', data?.total_contests], ['Live contests', data?.live_contests], ['Submissions', data?.total_submissions], ['Quantum jobs', data?.total_quantum_jobs]]; return <><div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 16 }}><h2 style={{ margin: 0 }}>Platform metrics</h2><button className="btn btn-secondary btn-sm" onClick={refresh}>Refresh</button></div><div className="stats-grid">{cards.map(([name, value]) => <div className="stat-card" key={name}><div className="stat-value">{loading ? '—' : value ?? 'Unavailable'}</div><div className="stat-label">{name}</div></div>)}</div></>; }
function Search({ query, setQuery, refresh, createLabel, create }) { return <div style={{ display: 'flex', gap: 8, marginBottom: 16, flexWrap: 'wrap' }}><input className="form-input" style={{ maxWidth: 360 }} value={query} placeholder="Search by title or name" onChange={e => setQuery(e.target.value)} /><button className="btn btn-secondary" onClick={refresh}>Search</button>{create && <button className="btn btn-primary" onClick={create}>+ {createLabel}</button>}</div>; }
function Users({ rows, loading, query, setQuery, refresh, updateRole, saving }) { return <><Search query={query} setQuery={setQuery} refresh={refresh} /><div className="card"><h3>Users</h3>{loading ? <Empty text="Loading…" /> : <table style={{ width: '100%', textAlign: 'left' }}><thead><tr><th>Name</th><th>Role</th><th>Knowledge</th><th>XP</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td>{row.full_name || 'Unnamed user'}</td><td><select className="form-input" value={row.role} disabled={saving === row.id} onChange={e => updateRole(row.id, e.target.value)}><option value="student">Student</option><option value="admin">Admin</option></select></td><td>{row.knowledge_score ?? '—'}%</td><td>{row.total_xp ?? 0}</td></tr>)}</tbody></table>}</div></>; }
function Settings({ data, loading, save }) { const [form, setForm] = useState({ contest_submission_limit: 10, allow_contest_resubmissions: true, maintenance_message: '' }); const [saving, setSaving] = useState(false); useEffect(() => { if (data) setForm(data); }, [data]); if (loading) return <div className="card"><Empty text="Loading…" /></div>; const submit = async e => { e.preventDefault(); setSaving(true); try { await save({ ...form, contest_submission_limit: Number(form.contest_submission_limit) }); } finally { setSaving(false); } }; return <form className="grid grid-2" onSubmit={submit}><section className="card"><h2>Contest settings</h2><label>Submission limit per problem<input className="form-input" type="number" min="1" max="50" value={form.contest_submission_limit} onChange={e => setForm({ ...form, contest_submission_limit: e.target.value })} /></label><label style={{ display: 'block', marginTop: 16 }}><input type="checkbox" checked={form.allow_contest_resubmissions} onChange={e => setForm({ ...form, allow_contest_resubmissions: e.target.checked })} /> Allow participants to resubmit</label><button className="btn btn-primary" style={{ marginTop: 18 }} disabled={saving}>{saving ? 'Saving…' : 'Save settings'}</button></section><section className="card"><h2>Platform notice</h2><label>Maintenance message<textarea className="form-input" rows="5" maxLength="500" value={form.maintenance_message} onChange={e => setForm({ ...form, maintenance_message: e.target.value })} /></label><p style={{ color: 'var(--text-muted)', fontSize: '.82rem' }}>Secrets are never saved here.</p></section></form>; }
function Content({ title, rows, loading, query, setQuery, refresh, create, edit, archive }) { return <><Search query={query} setQuery={setQuery} refresh={refresh} createLabel={`New ${title.slice(0, -1)}`} create={create} /><Records rows={rows} loading={loading} edit={edit} archive={archive} /></>; }
function Records({ rows, loading, edit, archive, audit, refresh }) { const fields = audit ? ['action', 'entity_type', 'entity_id', 'created_at'] : ['title', 'status', 'sort_order', 'updated_at']; return <div className="card"><div style={{ display: 'flex', justifyContent: 'space-between' }}><h3>{audit ? 'Append-only audit log' : 'Records'}</h3>{refresh && <button className="btn btn-secondary btn-sm" onClick={refresh}>Refresh</button>}</div>{loading ? <Empty text="Loading…" /> : !rows.length ? <Empty text="No records found." /> : <div style={{ overflowX: 'auto' }}><table style={{ width: '100%', textAlign: 'left' }}><thead><tr>{fields.map(field => <th key={field}>{field.replace('_', ' ')}</th>)}{edit && <th>Actions</th>}</tr></thead><tbody>{rows.map(row => <tr key={row.id}>{fields.map(field => <td key={field}>{field.includes('_at') ? new Date(row[field]).toLocaleString() : String(row[field] ?? '—')}</td>)}{edit && <td><button className="text-action" onClick={() => edit(row)}>Edit</button> <button className="text-action danger" onClick={() => archive(row)}>Archive</button></td>}</tr>)}</tbody></table></div>}</div>; }
function Editor({ value, title, close, save }) { const [name, setName] = useState(value.title || ''); const [description, setDescription] = useState(value.description || ''); const [status, setStatus] = useState(value.status || 'draft'); const [saving, setSaving] = useState(false); const submit = async e => { e.preventDefault(); setSaving(true); try { await save({ title: name, description: description || null, status, sort_order: Number(value.sort_order || 0), metadata: value.metadata || {} }); } finally { setSaving(false); } }; return <div className="modal-overlay"><form className="modal" onSubmit={submit}><h2>{value.id ? `Edit ${title.slice(0, -1)}` : `New ${title.slice(0, -1)}`}</h2><label>Title<input className="form-input" required maxLength="200" value={name} onChange={e => setName(e.target.value)} /></label><label>Description<textarea className="form-input" rows="5" value={description} onChange={e => setDescription(e.target.value)} /></label><label>Status<select className="form-input" value={status} onChange={e => setStatus(e.target.value)}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label><div style={{ display: 'flex', gap: 8, justifyContent: 'flex-end', marginTop: 18 }}><button type="button" className="btn btn-secondary" onClick={close}>Cancel</button><button className="btn btn-primary" disabled={saving}>{saving ? 'Saving…' : 'Save'}</button></div></form></div>; }
function Empty({ text }) { return <p style={{ color: 'var(--text-muted)', padding: 18 }}>{text}</p>; }
