import { useEffect, useState } from 'react';
import { adminApi } from '../../services/quantumApi.js';

const SECTIONS = [['overview', 'Overview'], ['users', 'Users'], ['modules', 'Modules'], ['topics', 'Topics'], ['resources', 'Resources'], ['questions', 'Questions'], ['circuit-challenges', 'Circuit challenges'], ['coding-challenges', 'Coding challenges'], ['achievements', 'Achievements'], ['projects', 'Projects'], ['announcements', 'Announcements'], ['audit', 'Audit log']];
const CONTENT = new Set(SECTIONS.map(([key]) => key).filter(key => !['overview', 'users', 'audit'].includes(key)));

export default function AdminPanel() {
  const [section, setSection] = useState('overview');
  const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [query, setQuery] = useState(''); const [editor, setEditor] = useState(null); const [notice, setNotice] = useState('');
  const load = async () => { setLoading(true); setError(''); try { const response = section === 'overview' ? await adminApi.dashboard() : section === 'users' ? await adminApi.users(query) : section === 'audit' ? await adminApi.auditLogs() : await adminApi.content(section, query); setData(response); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  useEffect(() => { setQuery(''); setEditor(null); load(); }, [section]);
  const rows = data?.items || data?.users || data?.logs || [];
  const save = async values => { try { if (editor?.id) await adminApi.updateContent(section, editor.id, values); else await adminApi.createContent(section, values); setEditor(null); setNotice('Saved.'); load(); } catch (e) { setError(e.message); } };
  const archive = async item => { if (!window.confirm(`Archive “${item.title}”? Historical records will be preserved.`)) return; try { await adminApi.archiveContent(section, item.id); setNotice('Archived.'); load(); } catch (e) { setError(e.message); } };
  const label = SECTIONS.find(([key]) => key === section)?.[1];
  return <div className="page fade-in"><div className="page-header"><h1 className="page-title">⚙️ Admin Dashboard</h1><p className="page-subtitle">Secure management for platform content and operations.</p></div><div className="tabs" style={{ marginBottom: 18, overflowX: 'auto' }}>{SECTIONS.map(([key, name]) => <button key={key} className={`tab ${section === key ? 'active' : ''}`} onClick={() => setSection(key)}>{name}</button>)}</div>{notice && <div className="tag tag-success" style={{ marginBottom: 14 }}>{notice}</div>}{error && <div className="card" style={{ color: 'var(--danger)', marginBottom: 14 }}>{error} <button className="btn btn-secondary btn-sm" onClick={load}>Retry</button></div>}{section === 'overview' && <Overview metrics={data?.metrics} loading={loading} onRefresh={load} />}{section === 'users' && <Users rows={rows} loading={loading} query={query} setQuery={setQuery} onSearch={load} onRefresh={load} />}{section === 'audit' && <Audit rows={rows} loading={loading} onRefresh={load} />}{CONTENT.has(section) && <Content title={label} rows={rows} loading={loading} query={query} setQuery={setQuery} onSearch={load} onCreate={() => setEditor({})} onEdit={setEditor} onArchive={archive} />}{editor && <Editor value={editor} title={label} onClose={() => setEditor(null)} onSave={save} />}</div>;
}

function Overview({ metrics, loading, onRefresh }) { const cards = [['Users', metrics?.total_users], ['Modules', metrics?.total_modules], ['Published modules', metrics?.published_modules], ['Topics', metrics?.total_topics], ['Contests', metrics?.total_contests], ['Live contests', metrics?.live_contests], ['Submissions', metrics?.total_submissions], ['Quantum jobs', metrics?.total_quantum_jobs]]; return <><div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 16 }}><h2 style={{ margin: 0 }}>Platform metrics</h2><button className="btn btn-secondary btn-sm" onClick={onRefresh}>Refresh</button></div><div className="stats-grid">{cards.map(([name, value]) => <div className="stat-card" key={name}><div className="stat-value">{loading ? '—' : value ?? 'Unavailable'}</div><div className="stat-label">{name}</div></div>)}</div><div className="card" style={{ marginTop: 20 }}><h3>Recent admin activity</h3>{(metrics?.recent_activity || []).length ? metrics.recent_activity.map((row, i) => <div key={i} style={{ padding: '10px 0', borderBottom: '1px solid var(--border-glass)' }}>{row.action} · {row.entity_type}<small style={{ marginLeft: 8, color: 'var(--text-muted)' }}>{new Date(row.created_at).toLocaleString()}</small></div>) : <Empty text="No persisted admin activity yet." />}</div></>; }
function Content({ title, rows, loading, query, setQuery, onSearch, onCreate, onEdit, onArchive }) { return <><Toolbar query={query} setQuery={setQuery} onSearch={onSearch} createLabel={`New ${title.slice(0, -1)}`} onCreate={onCreate} /><div className="card"><h3>{title}</h3>{loading ? <Empty text="Loading…" /> : !rows.length ? <Empty text={`No ${title.toLowerCase()} yet.`} /> : <Table rows={rows} onEdit={onEdit} onArchive={onArchive} />}</div></>; }
function Users({ rows, loading, query, setQuery, onSearch, onRefresh }) { return <><Toolbar query={query} setQuery={setQuery} onSearch={onSearch} /><div className="card"><div style={{ display: 'flex', justifyContent: 'space-between' }}><h3>Users</h3><button className="btn btn-secondary btn-sm" onClick={onRefresh}>Refresh</button></div>{loading ? <Empty text="Loading…" /> : !rows.length ? <Empty text="No users found." /> : <div style={{ overflowX: 'auto' }}><table style={{ width: '100%', textAlign: 'left' }}><thead><tr><th>Name</th><th>Role</th><th>Knowledge</th><th>XP</th><th>Joined</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td>{row.full_name || 'Unnamed user'}</td><td><span className="tag tag-info">{row.role}</span></td><td>{row.knowledge_score ?? '—'}%</td><td>{row.total_xp ?? 0}</td><td>{new Date(row.created_at).toLocaleDateString()}</td></tr>)}</tbody></table></div>}</div></>; }
function Audit({ rows, loading, onRefresh }) { return <div className="card"><div style={{ display: 'flex', justifyContent: 'space-between' }}><h3>Append-only audit log</h3><button className="btn btn-secondary btn-sm" onClick={onRefresh}>Refresh</button></div>{loading ? <Empty text="Loading…" /> : !rows.length ? <Empty text="No audit records yet." /> : <Table rows={rows} audit />}</div>; }
function Toolbar({ query, setQuery, onSearch, createLabel, onCreate }) { return <div style={{ display: 'flex', gap: 8, marginBottom: 16, flexWrap: 'wrap' }}><input className="form-input" style={{ maxWidth: 360 }} value={query} placeholder="Search by title or name" onChange={e => setQuery(e.target.value)} /><button className="btn btn-secondary" onClick={onSearch}>Search</button>{onCreate && <button className="btn btn-primary" onClick={onCreate}>+ {createLabel}</button>}</div>; }
function Table({ rows, onEdit, onArchive, audit }) { const columns = audit ? ['action', 'entity_type', 'entity_id', 'created_at'] : ['title', 'status', 'sort_order', 'updated_at']; return <div style={{ overflowX: 'auto' }}><table style={{ width: '100%', textAlign: 'left' }}><thead><tr>{columns.map(x => <th key={x}>{x.replace('_', ' ')}</th>)}{onEdit && <th>Actions</th>}</tr></thead><tbody>{rows.map(row => <tr key={row.id}>{columns.map(key => <td key={key}>{key.includes('_at') ? new Date(row[key]).toLocaleString() : String(row[key] ?? '—')}</td>)}{onEdit && <td><button className="text-action" onClick={() => onEdit(row)}>Edit</button> <button className="text-action danger" onClick={() => onArchive(row)}>Archive</button></td>}</tr>)}</tbody></table></div>; }
function Editor({ value, title, onClose, onSave }) { const [titleValue, setTitle] = useState(value.title || ''); const [description, setDescription] = useState(value.description || ''); const [status, setStatus] = useState(value.status || 'draft'); const [saving, setSaving] = useState(false); const submit = async e => { e.preventDefault(); setSaving(true); await onSave({ title: titleValue, description: description || null, status, sort_order: Number(value.sort_order || 0), metadata: value.metadata || {} }); setSaving(false); }; return <div className="modal-overlay"><form className="modal" onSubmit={submit}><h2>{value.id ? `Edit ${title.slice(0, -1)}` : `New ${title.slice(0, -1)}`}</h2><label>Title<input className="form-input" required maxLength="200" value={titleValue} onChange={e => setTitle(e.target.value)} /></label><label>Description<textarea className="form-input" rows="5" value={description} onChange={e => setDescription(e.target.value)} /></label><label>Status<select className="form-input" value={status} onChange={e => setStatus(e.target.value)}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label><div style={{ display: 'flex', gap: 8, justifyContent: 'flex-end', marginTop: 18 }}><button type="button" className="btn btn-secondary" onClick={onClose}>Cancel</button><button className="btn btn-primary" disabled={saving}>{saving ? 'Saving…' : 'Save'}</button></div></form></div>; }
function Empty({ text }) { return <p style={{ color: 'var(--text-muted)', padding: 18 }}>{text}</p>; }
